project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - experiments/2026_6_22/plan_EnrichedT.qmd
    - experiments/2026_6_23/result_ON_EnrichedT.qmd
    - experiments_page.qmd
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for your editing contributions!"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "Lab Notebook"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "Home"
        href: index.qmd  
      - text: "Experiments"   
        href: experiments_page.qmd
    right:
    - icon: github
      href: https://github.com/CyrusMartinian/LabNotebook
      aria-label: GitHub

  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
format:
  html:
    css: styles.scss

