project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - /experiments/2026_6_22/plan_EnrichedT.qmd
    - /experiments/2026_6_22/plan_single_EnrichedT.qmd
    - /experiments/2026_6_22/result_30min_EnrichedT.qmd
    - /experiments/2026_6_23/result_ON_EnrichedT.qmd
    - /experiments/2026_6_29/result_30min_CAR_1.qmd
    - /experiments/2026_6_29/plan_CAR_1.qmd
    - /experiments/2026_6_30/plan_and_result_30min_CAR_2.qmd
    - /experiments/2026_6_30/result_ON_CAR_1.qmd
    - /experiments/2026_07_01/result_ON_CAR_2.qmd
    - /experiments/2026_07_07/plan_ON_fixed_PBMC.qmd
    - /experiments/2026_07_08/result_ON_PBMC.qmd
    - /experiments/2026_07_27/plan_CAR3.qmd
    - /experiments/2026_07_27/plan_EnrichedT_SC.qmd
    - /experiments/2026_07_28/result_CAR3.qmd
    - /experiments/2026_07_28/result_ON_SC.qmd
website:
  page-navigation: true 
  title: "Lab Notebook"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - text: "Home"
        href: index.qmd  
    right:
    - icon: github
      href: https://github.com/CyrusMartinian/LabNotebook
      aria-label: GitHub
  sidebar:
    collapse-level: 1
    contents:
    - section: "June 22nd 2026"
      contents:
      - text: "Staining Enriched T cells"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_22/plan_EnrichedT.html
      - text: "Single Color Controls"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_22/plan_single_EnrichedT.html
      - text: "Result of Sequential Stain"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_22/result_30min_EnrichedT.html
    - section: "June 23rd 2026"
      contents:
      - text: "Result of Overnight Stain"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_23/result_ON_EnrichedT.html
    - section: "June 29th 2026"
      contents:
      - text: "Overnight & 30 min Staining of CAR T cells"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_29/plan_CAR_1.html
      - text: "Result of 30 min Stain of CAR T cells"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_29/result_30min_CAR_1.html
    - section: "June 30th 2026"
      contents:
      - text: "Staining of CAR T cells and 30 min Result"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_30/plan_and_result_30min_CAR_2.html
      - text: "Result of Overnight Stain of CAR T cells"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_6_22/result_ON_CAR_1.html
    - section: "July 1st 2026"
      contents:
      - text: "Result of Overnight stain & Re-stain of CAR T cells"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_01/result_ON_CAR_2.html
    - section: "July 7th 2026"
      contents:
      - text: "Fixation & Overnight Staining of PBMCs"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_07/plan_ON_fixed_PBMC.html
    - section: "July 8th 2026"
      contents:
      - text: "Results of Fixation & Overnight Stain of PBMCs"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_08/result_ON_PBMC.html
    - section: "July 27th 2026"
      contents:
      - text: "Revised Protocol Overnight CAR T Stain"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_27/plan_CAR3.html
      - text: "30 Minute & Overnight SC Controls"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_27/plan_EnrichedT_SC.html
    - section: "July 28th 2026"
      contents:
      - text: "Results of Overnight CAR T Stain"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_28/result_CAR3.html
      - text: "Results of 30 Minute & Overnight SC Controls"
        href: https://cyrusmartinian.github.io/LabNotebook/experiments/2026_07_01/result_ON_SC.html
        
        

  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
format:
  html:
    css: styles.scss

