---
title: "Backbone Stain Protocol"
theme: darkly
author: "Cyrus Martinian"
date: 2026-06-23
toc: TRUE
---

# Background Information
In an effort to optimize a high-parameter flow cytometry panel, previously run using sequential staining (cocktail 1, backbone, and cocktail 2), the backbone group of antibodies:fluorophore conjugates as well as the full stain were prepared at the previously tested antibody volume & concentration, and incubated for 30 minutes, as well as overnight.

# Backbone Stain Protocol for Enriched T Cells
## Day 1

1. Cryopreserved enriched T cells were thawed, centrifuged, and resuspended in a minimal amount of buffer solution
2. Fluorophore - conjugated antibodies, TruStain FcX (Fc blocking buffer), and SuperBright buffer (to mitigate aggregation of antibodies) were centrifuged at 4000 rpm for 1 minute
3. 5 uL of TruStain FcX was added to the total enriched T cell sample volume, cell sample was incubated for at least 5 minutes in the fridge
4. The backbone cocktail (antibodies known to stain well for this panel) was prepared for 2 samples, according to the following table (the volumes of antibody listed are per sample). 2 uL of SuperBright was added to the eppendorf tube prior to antibodies to mitigate aggregation.


| Marker | Fluorophore     | Volume (uL) |
| ------ | --------------- | ----------- |
| CD62L  | BUV395          | 5           |
| CD4    | BUV496          | 3           |
| CD8    | BUV510          | 2           |
| CD45RO | BV570           | 5           |
| CD3    | Spark Blue 550  | 5           |
| CD45RA | Alexa Fluor 700 | 1           |


5. 25 uL of enriched T cell sample was aliquoted into 3 5 mL FACS tubes, tubes were labled UN (unstained), BB-30 minute (backbone stain, 30 minute incubation), and BB-ON (backbone stain, overnight)
6. 20 uL of the backbone stain cocktail was added to the tubes labled BB-30 and BB-ON
7. BB-ON tube was placed in the fridge and left to incubate for 19 hours (overnight), and BB-30 was placed in the fridge and left to incubate for 30 minutes.
8. After 30 minutes, 1 mL of running buffer was added to BB-30 tube, and UN tube. Tubes were then centrifuged at 300xg for 5 minutes, supernatent was discarded
9. Pellets were resuspended in 180 uL of running buffer
10. 5 uL of 7-AAD viability dye was added to both BB-30 and UN tubes (should not have been added to UN)
11. BB-30 and UN tubes were incubated in the fridge for 5 minutes
12. BB-30, UN, and full stain (prepared by **NAME**) were run using the Aurora-4 Spectral Cytometer

## Day 2

13. BB-ON tube was retrieved from fridge, 1 mL of running buffer was added and sample was centrifuged at 300xg for 5 minutes, supernatent was discarded
14. pellet was resuspended in 180 uL of running buffer
15. 5 uL of 7-AAD viability dye was added to BB-ON tube
16. BB-ON tube was placed in fridge to incubate for 5 minutes
17. BB-ON, full stain-2 (at antibody concentrations previously tested, incubated overnight), and full stain-1 (at lower antibody concentrations, incubated overnight), were run using the Aurora-4 Spectral Cytometer